from typing import Literal
class Sat:
    """
    Class representing a SAT problem. It is initialized as a list of clauses and can be modified by adding new clauses. The solve method returns a solution to the problem, if it exists.
    :param clauses: A list of clauses, where each clause is a list of integers representing literals. Positive integers represent positive literals, while negative integers represent negated literals.
    """

    @property
    def model(self)->list[bool] | None: ...
    """
    A list of booleans representing the solution to the problem.
    """

    @property
    def stats(self)->Stats|None: ...
    """
    Retrieve the stats of the execution.
    """

    def __init__(self, clauses: list[list[int]]) -> None: ...
    def add_clause(self, clause: list[int]) -> None:
        """Adds a new clause to the SAT problem.

        Args:
            clause: A list of integers representing a clause, where positive integers represent positive literals and negative integers represent negated literals.
        """
        ...
    def solve(
        self, 
        algorithm: Literal["dpll", "cdcl"], 
        implication_point: Literal["uip","dip"], 
        preprocess: list[Literal["bva","bve","ges","ges_always","ges_lbd","ges_par","ges_random","ges_vsids","ges_utility","ges_compress","ges_trail","subsumption"]],
        inprocessing: list[Literal["bva","bve","ges","ges_always","ges_lbd","ges_par","ges_random","ges_vsids","ges_utility","ges_compress","ges_trail","subsumption"]],
        heuristics: Literal["vsids","random"], 
        drat_path: str|None = None,
        extension_guidance: dict[str, object]|None = None,
        extension_guidance_log_path: str|None = None,
        ) -> None:
        """Solve the SAT problem.

        Args:
            algorithm: The algorithm to use ("dpll" or "cdcl").
            implication_point: UIP/DIP mode for CDCL.
            preprocess: Preprocessing techniques to apply. GES modifiers are "ges_compress" (substitution only) and "ges_trail" (trail-touched clauses, then cursor fallback).
            inprocessing: Inprocessing techniques to apply. GES modifiers are "ges_compress" (substitution only) and "ges_trail" (trail-touched clauses, then cursor fallback).
            heuristics: Literal selection heuristic.
            drat_path: If given, write a DRAT proof to this path.
            extension_guidance: Optional compact guidance dictionary from Reduction.
            extension_guidance_log_path: Optional path for one line per observed DIP.
        """
        ...

class Stats:
    """
    Class representing the subclass inside sat to retrieve the stats of the execution, do not use it by itself.
    """

    @property
    def conflicts(self)-> int: ...
    """
    Retrieves the number of conflicts during the execution of the solver.
    """

    @property
    def restarts(self)-> int: ...
    """
    Retrieves the number of CDCL restarts during the execution of the solver.
    """

    @property
    def clauses_learnt(self)->int: ...
    """
    The number of clauses learned during CDCL sat solving. It is 0 if the solver was DPLL.
    """

    @property
    def clauses_deleted(self)->int: ...
    """
    The number of learnt clauses deleted during clause database reduction.
    """

    @property
    def clauses_subsumed(self)->int: ...
    """
    The number of clauses removed by subsumption preprocessing/inprocessing.
    """

    @property
    def subsumption_checks(self)->int: ...
    """
    The number of exact subset checks performed by lazy subsumption.
    """

    @property
    def minimized_literals(self)->int: ...
    """
    The number of literals removed by learned-clause minimization.
    """

    @property
    def clauses_kept(self)->int: ...
    """
    The number of learnt clauses still kept after clause database reductions.
    """

    @property
    def literals_learnt(self)->int: ...
    """
    The total number of auxiliary literals added by extension/DIP and BVA.
    """

    @property
    def extension_literals(self)->int: ...
    """
    The number of auxiliary extension literals added by DIP learning.
    """

    @property
    def dip_candidates_found(self)->int: ...
    @property
    def dip_unit_post_clauses(self)->int: ...
    @property
    def dip_glue_post_clauses(self)->int: ...
    @property
    def dip_lbd_rejections(self)->int: ...
    @property
    def dip_assigned_extension_rejections(self)->int: ...
    @property
    def dip_uip_fallbacks(self)->int: ...

    @property
    def guidance_checks(self)->int: ...
    @property
    def guidance_matches(self)->int: ...
    @property
    def guidance_unique_matches(self)->int: ...
    @property
    def guidance_stages_completed(self)->int: ...
    @property
    def guidance_deepest_level(self)->int: ...
    @property
    def guidance_best_progress(self)->int: ...

    @property
    def bva_literals(self)->int: ...
    """
    The number of auxiliary literals added by bounded variable addition.
    """

    @property
    def bva_candidates_attempted(self)->int: ...
    @property
    def bva_clause_visits(self)->int: ...
    @property
    def bva_clauses_saved(self)->int: ...
    @property
    def bva_source_clauses_replaced(self)->int: ...
    @property
    def bva_budget_exhaustions(self)->int: ...
    @property
    def bva_budget_increases(self)->int: ...
    @property
    def bva_budget_decreases(self)->int: ...
    @property
    def bva_current_budget(self)->int: ...
    @property
    def bva_peak_budget(self)->int: ...
    @property
    def bva_binary_and_factors(self)->int: ...
    @property
    def bva_non_binary_and_factors(self)->int: ...
    @property
    def bva_ite_factors(self)->int: ...
    @property
    def bva_xor_factors(self)->int: ...

    @property
    def bve_eliminated_variables(self)->int: ...
    """
    The number of variables eliminated by bounded variable elimination.
    """

    @property
    def bve_resolvents(self)->int: ...
    """
    The number of resolvents added by bounded variable elimination.
    """

    @property
    def global_extension_substitution(self)->int: ...
    """
    The number of clauses compressed through exact global extension substitution.
    """

    @property
    def ges_clauses_inspected(self)->int: ...
    @property
    def ges_noop_rewrites(self)->int: ...
    @property
    def ges_rewrites_rejected(self)->int: ...
    @property
    def ges_lbd_improvements(self)->int: ...
    @property
    def ges_vsids_improvements(self)->int: ...
    @property
    def ges_utility_improvements(self)->int: ...
    @property
    def ges_literals_removed(self)->int: ...
    @property
    def ges_binary_clauses_compressed(self)->int: ...
    """Permanent binary clauses compressed to units by exact extension substitution."""
    @property
    def ges_clauses_unrolled(self)->int: ...
    @property
    def ges_dip_extensions_unrolled(self)->int: ...
    @property
    def ges_bva_extensions_unrolled(self)->int: ...
    @property
    def ges_other_extensions_unrolled(self)->int: ...
    @property
    def ges_unrolled_source_literals(self)->int: ...
    @property
    def ges_unrolled_working_literals(self)->int: ...
    @property
    def ges_substitutions_after_unrolling(self)->int: ...
    @property
    def ges_substitutions_to_dip(self)->int: ...
    @property
    def ges_substitutions_to_bva(self)->int: ...
    @property
    def ges_substitutions_to_other(self)->int: ...
    @property
    def ges_rewrites_after_unrolling(self)->int: ...
    @property
    def ges_rerolled_rewrites_after_unrolling(self)->int: ...
    @property
    def ges_unrolled_rewrites_rejected(self)->int: ...
    @property
    def ges_unrolled_rewrites_restored(self)->int: ...
    @property
    def ges_replacements_used(self)->int: ...
    """GES replacements used at least once as a reason or during conflict analysis."""
    @property
    def ges_replacement_reason_uses(self)->int: ...
    """Successful implications and active reason transfers, counted per use."""
    @property
    def ges_replacement_analysis_uses(self)->int: ...
    """Source-clause occurrences in conflict analysis, including the conflict clause."""
    @property
    def ges_replacements_deleted_unused(self)->int: ...
    """GES replacements deleted without any reason or analysis use; excludes GC."""
    @property
    def ges_budget_increases(self)->int: ...
    @property
    def ges_budget_decreases(self)->int: ...
    @property
    def ges_current_budget(self)->int: ...
    @property
    def ges_peak_budget(self)->int: ...
    @property
    def ges_trail_unique_touches(self)->int: ...
    @property
    def ges_trail_clauses_selected(self)->int: ...
    @property
    def ges_trail_cursor_selected(self)->int: ...
    @property
    def ges_trail_duplicate_skips(self)->int: ...

    @property
    def avg_clause_length(self)->float:...
    """
    The average length of the clauses learnt, it is often a good measure of relevance of the conflicts.
    """

    def elapsed_secs(self)->int:...
    """
    Returns the elapsed time of the solving in seconds.
    """

    def elapsed_nanos(self)->int:...
    """
    Returns the elapsed time of the solving in nanoseconds.
    """

    def elapsed_millis(self)->int:...
    """
    Returns the elapsed time of the solving in milliseconds.
    """

    def preprocessing_millis(self)->float:...
    def solving_millis(self)->float:...
    def propagation_millis(self)->float:...
    def conflict_analysis_millis(self)->float:...
    def clause_minimization_millis(self)->float:...
    def clause_learning_millis(self)->float:...
    def db_reduction_millis(self)->float:...
    def subsumption_millis(self)->float:...
    def restart_millis(self)->float:...
    def inprocessing_millis(self)->float:...

    def __str__(self)->str:...
    """
    Prints a formatted view of all the stats.
    """
